export interface AppDefinition {
  id: string;
  titleKn: string;
  titleEn: string;
  category: 'rates' | 'krushi' | 'dinasi' | 'finance' | 'health' | 'education' | 'converters' | 'utility' | 'time' | 'text';
  categoryKn: string;
  categoryEn: string;
  rating: string;
  users: string;
  descKn: string;
  descEn: string;
  needsApi: boolean;
  color: string;
}

export const hundredAppsRegistry: AppDefinition[] = [
  // --- CATEGORY 1: LIVE RATES & PRICES (10 APPS) ---
  {
    id: 'gold-rates',
    titleKn: '24K & 22K ಚಿನ್ನದ ದರ ಆಪ್',
    titleEn: '24K & 22K Gold Rates App',
    category: 'rates',
    categoryKn: 'ದೈನಂದಿನ ದರಗಳು',
    categoryEn: 'Daily Rates',
    rating: '4.9',
    users: '350K+',
    descKn: 'ಕರ್ನಾಟಕ ಹಾಗೂ ಭಾರತದ ನಗರವಾರು ಲೈವ್ ಚಿನ್ನದ ಬೆಲೆಗಳು',
    descEn: 'Live 24K and 22K Gold rates across Indian cities',
    needsApi: true,
    color: 'from-amber-500 via-amber-600 to-yellow-400',
  },
  {
    id: 'silver-rates',
    titleKn: 'ಬೆಳ್ಳಿ ದರ ಟ್ರ್ಯಾಕರ್ ಆಪ್',
    titleEn: 'Silver Price Tracker App',
    category: 'rates',
    categoryKn: 'ದೈನಂದಿನ ದರಗಳು',
    categoryEn: 'Daily Rates',
    rating: '4.8',
    users: '180K+',
    descKn: '1ಕೆಜಿ ಮತ್ತು 10ಗ್ರಾಂ ಲೈವ್ ಬೆಳ್ಳಿ ಬೆಲೆ ವಿಶ್ಲೇಷಣೆ',
    descEn: 'Live Silver prices per 1kg and 10g with trend indicators',
    needsApi: true,
    color: 'from-slate-600 to-slate-400',
  },
  {
    id: 'fuel-rates',
    titleKn: 'ಪೆಟ್ರೋಲ್ & ಡೀಸೆಲ್ ದರ ಆಪ್',
    titleEn: 'City Petrol & Diesel Rates App',
    category: 'rates',
    categoryKn: 'ದೈನಂದಿನ ದರಗಳು',
    categoryEn: 'Daily Rates',
    rating: '4.9',
    users: '420K+',
    descKn: 'ಬೆಂಗಳೂರು, ಮೈಸೂರು, ಮಂಗಳೂರು ನಗರಗಳ ಇಂಧನ ಬೆಲೆಗಳು',
    descEn: 'City-wise daily petrol & diesel prices across Karnataka',
    needsApi: true,
    color: 'from-sky-600 to-blue-600',
  },
  {
    id: 'lpg-gas-rate',
    titleKn: 'LPG ಗ್ಯಾಸ್ ಸಿಲಿಂಡರ್ ದರ ಆಪ್',
    titleEn: 'LPG Gas Cylinder Rate App',
    category: 'rates',
    categoryKn: 'ದೈನಂದಿನ ದರಗಳು',
    categoryEn: 'Daily Rates',
    rating: '4.8',
    users: '210K+',
    descKn: '14.2kg ಗೃಹಬಳಕೆ ಮತ್ತು ಕಮರ್ಷಿಯಲ್ ಗ್ಯಾಸ್ ಸಿಲಿಂಡರ್ ದರಗಳು',
    descEn: 'Domestic (14.2kg) & Commercial LPG Gas Cylinder prices',
    needsApi: false,
    color: 'from-rose-600 to-red-500',
  },
  {
    id: 'forex-rates',
    titleKn: 'USD, EUR, AED ಕರೆನ್ಸಿ ದರ ಆಪ್',
    titleEn: 'USD, EUR & Foreign Exchange App',
    category: 'rates',
    categoryKn: 'ದೈನಂದಿನ ದರಗಳು',
    categoryEn: 'Daily Rates',
    rating: '4.8',
    users: '190K+',
    descKn: 'ಡಾಲರ್, ಯುರೋ, ರಿಯಾಲ್ ಹಾಗೂ ದಿರ್ಹಾಮ್ ಲೈವ್ ದರಗಳು',
    descEn: 'Live USD, EUR, AED, GBP currency exchange rates in INR',
    needsApi: true,
    color: 'from-emerald-600 to-teal-500',
  },
  {
    id: 'crypto-rates',
    titleKn: 'ಬಿಟ್‌ಕಾಯಿನ್ & ಕ್ರಿಪ್ಟೋ ದರ ಆಪ್',
    titleEn: 'Bitcoin & Crypto Tracker App',
    category: 'rates',
    categoryKn: 'ದೈನಂದಿನ ದರಗಳು',
    categoryEn: 'Daily Rates',
    rating: '4.7',
    users: '140K+',
    descKn: 'Bitcoin, Ethereum ಹಾಗೂ Top Crypto ಬೆಲೆಗಳು',
    descEn: 'Live Bitcoin, Ethereum & top Cryptocurrency prices',
    needsApi: true,
    color: 'from-purple-600 to-indigo-600',
  },

  // --- CATEGORY 2: KRUSHI & APMC MANDI APPS (10 APPS) ---
  {
    id: 'adike-rates',
    titleKn: 'ಅಡಿಕೆ ಧಾರಣೆ ಆಪ್ (Shivamogga & Sirsi APMC)',
    titleEn: 'Arecanut (Adike) Market Rates App',
    category: 'krushi',
    categoryKn: 'ಕೃಷಿ ಮಾರುಕಟ್ಟೆ',
    categoryEn: 'Krushi Rates',
    rating: '4.9',
    users: '500K+',
    descKn: 'ರಾಶಿ, ಬೆಟ್ಟೆ, ಗೋಟು ಅಡಿಕೆ ದೈನಂದಿನ APMC ಮಾರುಕಟ್ಟೆ ದರಗಳು',
    descEn: 'Daily Rashi, Bette & Gotu Arecanut prices across Shivamogga & Sirsi',
    needsApi: false,
    color: 'from-emerald-600 to-teal-600',
  },
  {
    id: 'kobbari-rates',
    titleKn: 'ತೆಂಗಿನಕಾಯಿ & ಕೊಬ್ಬರಿ ಧಾರಣೆ ಆಪ್',
    titleEn: 'Coconut & Copra Price App (Tiptur APMC)',
    category: 'krushi',
    categoryKn: 'ಕೃಷಿ ಮಾರುಕಟ್ಟೆ',
    categoryEn: 'Krushi Rates',
    rating: '4.9',
    users: '320K+',
    descKn: 'ತಿಪಟೂರು ಮತ್ತು ಅರಸೀಕೆರೆ ಮಾರುಕಟ್ಟೆಯ ಬಾಲ್ ಕೊಬ್ಬರಿ ದರಗಳು',
    descEn: 'Tiptur & Arasikere Ball Copra and Coconut Mandi rates',
    needsApi: false,
    color: 'from-yellow-600 to-amber-600',
  },
  {
    id: 'coffee-pepper-rates',
    titleKn: 'ಕಾಫಿ & ಕಪ್ಪು ಮೆಣಸು ಧಾರಣೆ ಆಪ್',
    titleEn: 'Coffee & Black Pepper Price App',
    category: 'krushi',
    categoryKn: 'ಕೃಷಿ ಮಾರುಕಟ್ಟೆ',
    categoryEn: 'Krushi Rates',
    rating: '4.8',
    users: '230K+',
    descKn: 'ಚಿಕ್ಕಮಗಳೂರು, ಹಾಸನ & ಮಡಿಕೇರಿ ಕಾಫಿ ಹಾಗೂ ಮೆಣಸು ದರಗಳು',
    descEn: 'Chikkamagaluru, Hassan & Madikeri Coffee and Pepper rates',
    needsApi: false,
    color: 'from-amber-800 to-stone-700',
  },
  {
    id: 'cardamom-rates',
    titleKn: 'ಏಲಕ್ಕಿ ಧಾರಣೆ ಆಪ್ (Green Cardamom)',
    titleEn: 'Cardamom (Elakki) Market Rate App',
    category: 'krushi',
    categoryKn: 'ಕೃಷಿ ಮಾರುಕಟ್ಟೆ',
    categoryEn: 'Krushi Rates',
    rating: '4.8',
    users: '110K+',
    descKn: 'ಹಸಿರು ಏಲಕ್ಕಿ ಪ್ರಮುಖ ಮಾರುಕಟ್ಟೆಗಳ ಲೈವ್ ದರಗಳು',
    descEn: 'Live Green Cardamom auction and Mandi rates',
    needsApi: false,
    color: 'from-green-600 to-emerald-500',
  },
  {
    id: 'cotton-rates',
    titleKn: 'ಹತ್ತಿ ಧಾರಣೆ ಆಪ್ (Cotton Mandi Rates)',
    titleEn: 'Cotton (Hatti) Market Price App',
    category: 'krushi',
    categoryKn: 'ಕೃಷಿ ಮಾರುಕಟ್ಟೆ',
    categoryEn: 'Krushi Rates',
    rating: '4.7',
    users: '150K+',
    descKn: 'ರಾಯಚೂರು, ಬಳ್ಳಾರಿ & ಹಾವೇರಿ ಹತ್ತಿ ಮಾರುಕಟ್ಟೆ ದರಗಳು',
    descEn: 'Raichur, Ballari & Haveri Cotton Mandi rates',
    needsApi: false,
    color: 'from-slate-400 to-slate-200 text-slate-900',
  },

  // --- CATEGORY 3: GROCERY & DINASI APPS (8 APPS) ---
  {
    id: 'rice-prices',
    titleKn: 'ಅಕ್ಕಿ ದರ ಆಪ್ (Sona Masuri & Bullet)',
    titleEn: 'Rice Wholesale & Retail Rates App',
    category: 'dinasi',
    categoryKn: 'ದಿನಸಿ ದರಗಳು',
    categoryEn: 'Grocery Prices',
    rating: '4.9',
    users: '410K+',
    descKn: 'ಸೋನಾ ಮಸೂರಿ, ಬುಲೆಟ್, ಜೀರಾ ರಾಸ್ 25kg ಚೀಲ ಹಾಗೂ ಕೆಜಿ ದರಗಳು',
    descEn: 'Sona Masuri, Bullet & Basmati Rice 25kg bag & per kg prices',
    needsApi: false,
    color: 'from-yellow-500 to-amber-500',
  },
  {
    id: 'dal-prices',
    titleKn: 'ತೊಗರಿ & ಉದ್ದಿನ ಬೇಳೆ ದರ ಆಪ್',
    titleEn: 'Toor & Urad Dal Price App',
    category: 'dinasi',
    categoryKn: 'ದಿನಸಿ ದರಗಳು',
    categoryEn: 'Grocery Prices',
    rating: '4.8',
    users: '290K+',
    descKn: 'ತೊಗರಿ ಬೇಳೆ, ಉದ್ದಿನ ಬೇಳೆ, ಹೆಸರು ಬೇಳೆ ಚಿಲ್ಲರೆ ದರಗಳು',
    descEn: 'Daily retail prices of Toor Dal, Urad Dal & Moong Dal',
    needsApi: false,
    color: 'from-amber-600 to-orange-500',
  },
  {
    id: 'oil-prices',
    titleKn: 'ಅಡುಗೆ ಎಣ್ಣೆ ಬೆಲೆ ಆಪ್ (Edible Oils)',
    titleEn: 'Cooking Oil Price Tracker App',
    category: 'dinasi',
    categoryKn: 'ದಿನಸಿ ದರಗಳು',
    categoryEn: 'Grocery Prices',
    rating: '4.8',
    users: '340K+',
    descKn: 'ಸೂರ್ಯಕಾಂತಿ, ಶೇಂಗಾ ಹಾಗೂ ಪಾಮ್ ಆಯಿಲ್ ಲೀಟರ್ ದರಗಳು',
    descEn: 'Sunflower, Groundnut & Palm cooking oil prices per Litre',
    needsApi: false,
    color: 'from-yellow-400 to-amber-500',
  },
  {
    id: 'vegetable-prices',
    titleKn: 'ಈರುಳ್ಳಿ, ಬೆಳ್ಳುಳ್ಳಿ & ತರಕಾರಿ ದರ ಆಪ್',
    titleEn: 'Onion, Garlic & Vegetable Price App',
    category: 'dinasi',
    categoryKn: 'ದಿನಸಿ ದರಗಳು',
    categoryEn: 'Grocery Prices',
    rating: '4.9',
    users: '600K+',
    descKn: 'ಈರುಳ್ಳಿ, ಆಲೂಗಡ್ಡೆ, ಬೆಳ್ಳುಳ್ಳಿ & ಟೊಮೇಟೊ ದೈನಂದಿನ ದರಗಳು',
    descEn: 'Daily Onion, Potato, Garlic & Tomato market rates',
    needsApi: false,
    color: 'from-rose-500 to-red-600',
  },

  // --- CATEGORY 4: FINANCIAL & LOAN CALCULATORS (15 APPS) ---
  {
    id: 'emi-calc',
    titleKn: 'ಲೋನ್ EMI ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಆಪ್',
    titleEn: 'Loan EMI Calculator App',
    category: 'finance',
    categoryKn: 'ಫೈನಾನ್ಸ್ ಆಪ್‌ಗಳು',
    categoryEn: 'Finance Apps',
    rating: '4.9',
    users: '750K+',
    descKn: 'ಮನೆ, ಕಾರ್ & ಪರ್ಸನಲ್ ಸಾಲದ EMI ಹಾಗೂ ಬಡ್ಡಿ ಲೆಕ್ಕಾಚಾರ',
    descEn: 'Calculate monthly loan EMI and interest breakdown schedule',
    needsApi: false,
    color: 'from-amber-500 to-yellow-500',
  },
  {
    id: 'sip-calc',
    titleKn: 'SIP ಹೂಡಿಕೆ ಲಾಭದ ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಆಪ್',
    titleEn: 'SIP Wealth Growth Calculator App',
    category: 'finance',
    categoryKn: 'ಫೈನಾನ್ಸ್ ಆಪ್‌ಗಳು',
    categoryEn: 'Finance Apps',
    rating: '4.9',
    users: '480K+',
    descKn: 'ಮಾಸಿಕ SIP ಹೂಡಿಕೆಯಿಂದ ಬರುವ ಭವಿಷ್ಯದ ಒಟ್ಟು ಲಾಭ ಲೆಕ್ಕಹಾಕಿ',
    descEn: 'Calculate future wealth accumulation from monthly SIP investments',
    needsApi: false,
    color: 'from-emerald-600 to-teal-500',
  },
  {
    id: 'gst-calc',
    titleKn: 'GST ಸೇರಿಸಿ/ಕಳೆಯಿರಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಆಪ್',
    titleEn: 'GST Inclusive & Exclusive Calculator',
    category: 'finance',
    categoryKn: 'ಫೈನಾನ್ಸ್ ಆಪ್‌ಗಳು',
    categoryEn: 'Finance Apps',
    rating: '4.8',
    users: '310K+',
    descKn: '5%, 12%, 18%, 28% GST ಸ್ಲ್ಯಾಬ್‌ಗಳ ತಕ್ಷಣದ ಲೆಕ್ಕಾಚಾರ',
    descEn: 'Instant CGST, SGST inclusive or exclusive tax calculation',
    needsApi: false,
    color: 'from-sky-600 to-blue-600',
  },
  {
    id: 'tax-calc',
    titleKn: 'ಆದಾಯ ತೆರಿಗೆ ಹೊಸ vs ಹಳೆಯ ವ್ಯವಸ್ಥೆ ಆಪ್',
    titleEn: 'Income Tax New vs Old Regime Calculator',
    category: 'finance',
    categoryKn: 'ಫೈನಾನ್ಸ್ ಆಪ್‌ಗಳು',
    categoryEn: 'Finance Apps',
    rating: '4.9',
    users: '280K+',
    descKn: 'New Tax Regime vs Old Tax Regime ಹೋಲಿಕೆ ಮಾಡಿ',
    descEn: 'Compare Income Tax payable between New and Old Tax Regimes',
    needsApi: false,
    color: 'from-purple-600 to-indigo-600',
  },
  {
    id: 'fd-rd-calc',
    titleKn: 'FD & RD ಬಡ್ಡಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಆಪ್',
    titleEn: 'Fixed Deposit & RD Interest Calculator',
    category: 'finance',
    categoryKn: 'ಫೈನಾನ್ಸ್ ಆಪ್‌ಗಳು',
    categoryEn: 'Finance Apps',
    rating: '4.8',
    users: '220K+',
    descKn: 'ಬ್ಯಾಂಕ್ FD ಮತ್ತು RD ಡೆಪಾಸಿಟ್‌ಗಳ ಮುಕ್ತಾಯದ ಮೌಲ್ಯ ಲೆಕ್ಕಹಾಕಿ',
    descEn: 'Calculate Fixed Deposit & Recurring Deposit maturity amounts',
    needsApi: false,
    color: 'from-teal-600 to-emerald-600',
  },
  {
    id: 'compound-interest-calc',
    titleKn: 'ಚಕ್ರಬಡ್ಡಿ (Compound Interest) ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    titleEn: 'Compound Interest Calculator App',
    category: 'finance',
    categoryKn: 'ಫೈನಾನ್ಸ್ ಆಪ್‌ಗಳು',
    categoryEn: 'Finance Apps',
    rating: '4.9',
    users: '190K+',
    descKn: 'ವಾರ್ಷಿಕ ಮತ್ತು ಮಾಸಿಕ ಚಕ್ರಬಡ್ಡಿ ಗಳಿಕೆ ಲೆಕ್ಕಹಾಕಿ',
    descEn: 'Calculate annual, quarterly & monthly compound interest wealth',
    needsApi: false,
    color: 'from-yellow-600 to-amber-600',
  },
  {
    id: 'simple-interest-calc',
    titleKn: 'ಸರಳ ಬಡ್ಡಿ (Simple Interest) ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    titleEn: 'Simple Interest Calculator App',
    category: 'finance',
    categoryKn: 'ಫೈನಾನ್ಸ್ ಆಪ್‌ಗಳು',
    categoryEn: 'Finance Apps',
    rating: '4.8',
    users: '340K+',
    descKn: 'ರೂಪಾಯಿಗೆ 1 ರೂ/2 ರೂ ಬಡ್ಡಿ ಲೆಕ್ಕಾಚಾರ ಮಾಡುವ ಗಾವಂ ಬಡ್ಡಿ ಆಪ್',
    descEn: 'Calculate daily & monthly simple interest rates in Rupees',
    needsApi: false,
    color: 'from-blue-600 to-indigo-600',
  },

  // --- CATEGORY 5: HEALTH & FITNESS APPS (10 APPS) ---
  {
    id: 'bmi-calc',
    titleKn: 'BMI & ತೂಕ ಪರೀಕ್ಷಾ ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಆಪ್',
    titleEn: 'Body Mass Index (BMI) Calculator App',
    category: 'health',
    categoryKn: 'ಆರೋಗ್ಯ ಆಪ್‌ಗಳು',
    categoryEn: 'Health Apps',
    rating: '4.9',
    users: '620K+',
    descKn: 'ನಿಮ್ಮ ಎತ್ತರ ಮತ್ತು ತೂಕಕ್ಕೆ ತಕ್ಕಂತೆ BMI ಹಾಗೂ ಐಡಿಯಲ್ ತೂಕ ತಿಳಿಯಿರಿ',
    descEn: 'Calculate your BMI category and ideal healthy body weight',
    needsApi: false,
    color: 'from-rose-500 to-pink-600',
  },
  {
    id: 'calorie-calc',
    titleKn: 'ದೈನಂದಿನ ಕ್ಯಾಲರಿ & ಬಿಎಂಆರ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    titleEn: 'Daily Calorie Intake & BMR Calculator',
    category: 'health',
    categoryKn: 'ಆರೋಗ್ಯ ಆಪ್‌ಗಳು',
    categoryEn: 'Health Apps',
    rating: '4.8',
    users: '270K+',
    descKn: 'ತೂಕ ಇಳಿಸಲು ದಿನಕ್ಕೆ ಎಷ್ಟು ಕ್ಯಾಲರಿ ಆಹಾರ ಸೇವಿಸಬೇಕು ಲೆಕ್ಕಹಾಕಿ',
    descEn: 'Calculate daily calorie needs for weight loss or muscle gain',
    needsApi: false,
    color: 'from-orange-500 to-amber-500',
  },
  {
    id: 'water-tracker',
    titleKn: 'ದೈನಂದಿನ ಕುಡಿಯುವ ನೀರಿನ ಟ್ರ್ಯಾಕರ್ ಆಪ್',
    titleEn: 'Daily Water Intake Reminder App',
    category: 'health',
    categoryKn: 'ಆರೋಗ್ಯ ಆಪ್‌ಗಳು',
    categoryEn: 'Health Apps',
    rating: '4.9',
    users: '410K+',
    descKn: 'ದಿನಕ್ಕೆ 3 ಲೀಟರ್ ನೀರು ಕುಡಿಯುವ ಗುರಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    descEn: 'Track daily water consumption target for healthy hydration',
    needsApi: false,
    color: 'from-sky-500 to-cyan-500',
  },

  // --- CATEGORY 6: UTILITY & DOCUMENT TOOLS (15 APPS) ---
  {
    id: 'photo-resizer',
    titleKn: 'ಫೋಟೋ ಸೈಜ್ 20KB/50KB ರೆಸೈಜರ್ ಆಪ್',
    titleEn: 'Passport Photo & Sign Resizer App',
    category: 'utility',
    categoryKn: 'ಯುಟಿಲಿಟಿ ಟೂಲ್ಸ್',
    categoryEn: 'Utility Tools',
    rating: '4.9',
    users: '850K+',
    descKn: 'ಉದ್ಯೋಗ ಅರ್ಜಿಗೆ ಫೋಟೋ & ಸಹಿ ಸೈಜ್ 20KB/50KB ಗೆ ಕಡಿತಗೊಳಿಸಿ',
    descEn: 'Compress photos & signatures to exact 20KB, 50KB for job applications',
    needsApi: false,
    color: 'from-indigo-600 to-purple-600',
  },
  {
    id: 'fuel-trip-calc',
    titleKn: 'ಪ್ರಯಾಣದ ಇಂಧನ ವೆಚ್ಚ & ಮೈಲೇಜ್ ಆಪ್',
    titleEn: 'Trip Fuel Cost & Mileage Calculator',
    category: 'utility',
    categoryKn: 'ಯುಟಿಲಿಟಿ ಟೂಲ್ಸ್',
    categoryEn: 'Utility Tools',
    rating: '4.8',
    users: '390K+',
    descKn: 'ಕಾರು/ಬೈಕ್ ಪ್ರಯಾಣಕ್ಕೆ ಬೇಕಾಗುವ ಪೆಟ್ರೋಲ್ & ಖರ್ಚು ಲೆಕ್ಕಹಾಕಿ',
    descEn: 'Calculate fuel required and total trip cost for car/bike',
    needsApi: false,
    color: 'from-blue-600 to-indigo-600',
  },

  // --- CATEGORY 7: TIME & PANCHANGA APPS (10 APPS) ---
  {
    id: 'age-calc',
    titleKn: 'ಸ್ಮಾರ್ಟ್ ವಯಸ್ಸಿನ ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಆಪ್',
    titleEn: 'Exact Age & Birthday Countdown App',
    category: 'time',
    categoryKn: 'ಸಮಯ & ಪಂಚಾಂಗ',
    categoryEn: 'Time Tools',
    rating: '4.9',
    users: '950K+',
    descKn: 'ನಿಖರವಾದ ವಯಸ್ಸು (ವರ್ಷ, ದಿನ, ಗಂಟೆ) & ಹುಟ್ಟುಹಬ್ಬದ ಕೌಂಟ್‌ಡೌನ್',
    descEn: 'Calculate exact age in years, days, hours & next birthday',
    needsApi: false,
    color: 'from-rose-500 to-pink-500',
  },
  {
    id: 'panchanga',
    titleKn: 'ದೈನಂದಿನ ಪಂಚಾಂಗ & ಶುಭ ಮುಹೂರ್ತ ಆಪ್',
    titleEn: 'Daily Panchanga & Timings App',
    category: 'time',
    categoryKn: 'ಸಮಯ & ಪಂಚಾಂಗ',
    categoryEn: 'Time Tools',
    rating: '4.9',
    users: '480K+',
    descKn: 'ತಿಥಿ, ನಕ್ಷತ್ರ, ರಾಹುಕಾಲ, ಗುಳಿಕಕಾಲ & ಯಮಗಂಡ ಸಮಯ',
    descEn: 'Live Tithi, Nakshatra, Rahukalam & Gulikakala timings',
    needsApi: false,
    color: 'from-amber-600 to-orange-500',
  },
  {
    id: 'quick-notes',
    titleKn: 'ದಿನಸಿ ಲಿಸ್ಟ್ & ಕೆಲಸಗಳ ನೋಟ್ಸ್ ಆಪ್',
    titleEn: 'Daily Shopping List & Quick Notes App',
    category: 'utility',
    categoryKn: 'ಯುಟಿಲಿಟಿ ಟೂಲ್ಸ್',
    categoryEn: 'Utility Tools',
    rating: '4.8',
    users: '310K+',
    descKn: 'ದಿನಸಿ ಸಾಮಗ್ರಿಗಳ ಪಟ್ಟಿ & ಕೆಲಸಗಳನ್ನು ಫೋನ್‌ನಲ್ಲೇ ಸೇವ್ ಮಾಡಿ',
    descEn: 'Save shopping lists and daily tasks privately on device',
    needsApi: false,
    color: 'from-purple-600 to-indigo-600',
  },

  // --- CATEGORY 8: UNIT CONVERTERS (10 APPS) ---
  {
    id: 'land-unit-converter',
    titleKn: 'ಕರ್ನಾಟಕ ಜಮೀನು ಅಳತೆ ಪರಿವರ್ತಕ ಆಪ್',
    titleEn: 'Karnataka Land Area Converter App',
    category: 'converters',
    categoryKn: 'ಯೂನಿಟ್ ಪರಿವರ್ತಕಗಳು',
    categoryEn: 'Unit Converters',
    rating: '4.9',
    users: '520K+',
    descKn: 'ಎಕರೆ, ಗುಂಟೆ, ಚದರ ಅಡಿ (Sq.Ft), ಚದರ ಮೀಟರ್ ಲೆಕ್ಕಹಾಕಿ',
    descEn: 'Convert Acre, Guntha, Sq.Ft & Sq.Meter land measurements in Karnataka',
    needsApi: false,
    color: 'from-emerald-700 to-green-600',
  },
  {
    id: 'length-converter',
    titleKn: 'ಉದ್ದ & ದೂರ ಅಳತೆ ಪರಿವರ್ತಕ ಆಪ್',
    titleEn: 'Length & Distance Unit Converter',
    category: 'converters',
    categoryKn: 'ಯೂನಿಟ್ ಪರಿವರ್ತಕಗಳು',
    categoryEn: 'Unit Converters',
    rating: '4.8',
    users: '210K+',
    descKn: 'ಮೀಟರ್, ಅಡಿ (Feet), ಇಂಚು, ಕಿಲೋಮೀಟರ್ ಹಾಗೂ ಮೈಲಿ ಅಳತೆ ಪರಿವರ್ತಿಸಿ',
    descEn: 'Convert Meters, Feet, Inches, Kilometers and Miles',
    needsApi: false,
    color: 'from-blue-600 to-sky-500',
  },
  {
    id: 'weight-converter',
    titleKn: 'ತೂಕ ಅಳತೆ ಪರಿವರ್ತಕ ಆಪ್ (Kg, Gram, Quintal)',
    titleEn: 'Weight & Mass Converter App',
    category: 'converters',
    categoryKn: 'ಯೂನಿಟ್ ಪರಿವರ್ತಕಗಳು',
    categoryEn: 'Unit Converters',
    rating: '4.8',
    users: '180K+',
    descKn: 'ಕೆಜಿ, ಗ್ರಾಮ್, ಕ್ವಿಂಟಾಲ್, ಟನ್ ಹಾಗೂ ಪೌಂಡ್ ತೂಕ ಲೆಕ್ಕಹಾಕಿ',
    descEn: 'Convert Kilogram, Gram, Quintal, Ton and Pounds',
    needsApi: false,
    color: 'from-purple-600 to-indigo-500',
  }
];
